### ISSUE TITLE
Add component view cache feature

### ISSUE THREAD

**Issue by eguardiola** [NaluKit/nalu#10]
Use case:
-  A user is seeing the page 15 of a table of entities.
- The user clicks on editing an element so Nalu routes to the editing component.
- The user clicks the browsers backbutton and returns to the table but to the first page of the paged view not the 15º.

The component was destroyed and created a new one so the last status is lost. We should have a way to conditionally avoid this behaviour.

Can be similar to this: https://github.com/gilberto-torrezan/gwt-views#caching

On Vue we can obtain a similar results using keep-alive feature: https://vuejs.org/v2/api/#keep-alive

Angular has too this feature: https://medium.com/@gerasimov.pk/how-to-reuse-rendered-component-in-angular-2-3-with-routereusestrategy-64628e1ca3eb

**Comment by NaluKit** [comment]
We can add an attribute to the @Controller annotation, may be 'keep-alive = true', which will tell Nalu, to reuse a controller / component pair instead of always create a new one. Even it is reused, all method will be called and the parameters will be set. We can add a boolean - called 'cached' - to tell the controller, that it is reused instead of a new instance.

Is this what your a looking for?

**Comment by eguardiola** [comment]
I'm not sure if that will be enought. I need to think further on this. Will update this issue, thanks.

**Comment by eguardiola** [comment]
Example of one use case and hoe to deal with on Angular:

https://www.softwarearchitekt.at/post/2016/12/02/sticky-routes-in-angular-2-3-with-routereusestrategy.aspx

**Comment by FrankHossfeld** [comment]
Will plan this feature for version 1.0.0-rc-6.

**Comment by FrankHossfeld** [comment]
Will deploy a SNAPSHOT of version 1.0.0-rc-6 to Maven Central. Please test.

**Comment by FrankHossfeld** [comment]
Deployed!
