### ISSUE TITLE
Use browser history API for navigation instead of #hash.

### ISSUE THREAD

**Issue by slavap** [NaluKit/nalu#23]
As example see https://github.com/errai/errai/blob/master/errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/HistoryWrapper.java

I have slightly improved version of Errai class, see attached zip.
[browserhistory.zip](https://github.com/NaluKit/nalu/files/2697246/browserhistory.zip)

**Comment by FrankHossfeld** [comment]
Please, can you tell the benefit of using history API instead of #hash?

**Comment by slavap** [comment]
@FrankHossfeld See https://stackoverflow.com/a/10647861
Personally I prefer to have clean urls without #, but it's highly subjective 😀

**Comment by vegegoku** [comment]
I think this is a good chance to share my experience with history API in domino-mvp
First domino-mvp does not yet support auto-routing, but it expose a set of tools and APIs to make complex routing scenarios works, the APIs include commands, events and History API -state API-

lets starts with the basics :

- Presenter class provide a method to obtain the history class, so in a presenter to obtain an instance of the history class you call `history()`.

- To obtain the current history token you call `history().currentToken()`, this is immutable and every time called will return a new token instance representing the browser current url. the returned type is `HistoryToken`

- The HistoryToken provides a set of methods to ease the work with the token :

example browser url : `http://localhost:8080/path1/path2/path3?param1=v1&param2=v2#fragment1/fragment2`

#### manipulating the token

from the token class you can call the following : 
   
- `boolean startsWithPath(String path);` : return true if the token starts with the specified path, e.g : `token.startWithPath("path1")` returns `true`

- `boolean fragmentsStartsWith(String fragment);` : return true if the fragments part starts with specified fragment, e.g : `token.fragmentsStartsWith("fragment1")` returns `true`

- `boolean endsWithPath(String path);` : returns true if the paths parts ends with specified path, e.g : `token.endsWithPath("path3")` or `token.endsWithPath("path2/path3")` will return true.

- `boolean endsWithFragment(String fragment);` : same as endsWithPath but for fragments part 

- `boolean containsPath(String path);` returns true if the path specified presented in the token

- `boolean containsFragment(String fragment);` same as containsPath but for fragments

- `List<String> paths();` return a a list of all paths in the token , e.g : `token.paths()` return a list of `path1`, `path2`, `path3`
  
-  `List<String> fragments();` same as paths but for fragments part
   
- `String path();` return a full path part of the token, e.g : `token.path()` return `path1/path2/path3`

- `HistoryToken appendPath(String path);` append a new path to the end of the paths part

- `HistoryToken replacePath(String path, String replacement);` replace a path with new path

- `HistoryToken replaceLastPath(String replacement);` replace the last path part with a new path

 - `HistoryToken replaceLastFragment(String replacement);` replace last fragment part with a new fragment

- `HistoryToken replaceAllPaths(String newPath);` replace all paths with a new path

- `HistoryToken clearPaths();` remove all paths from the token

- `HistoryToken clearFragments();` remove all fragments from the token
 
- `HistoryToken removePath(String path);` remove specified from the token if exist

- `Map<String, String> queryParameters();` get all query parameters from the token

- `boolean hasQueryParameter(String name);` check if a query parameter present in the token

- `String parameterValue(String name);` get the value of the specified parameter if exist

 - `HistoryToken appendFragment(String fragment);` append a new fragment to the end of the fragments part

- `HistoryToken appendParameter(String name, String value);` append a new parameter to the end of the parameters part

- `HistoryToken replaceFragment(String fragment, String replacement);` replace fragment with a new fragment.

- `HistoryToken replaceParameter(String name, String replacementName, String replacementValue);` replace the parameter and its value with the specified name with a new parameter name and value

 - `HistoryToken removeParameter(String name);` remove parameter and its value

- `HistoryToken replaceAllFragments(String newFragment);` replace all fragments with a new fargment

- `HistoryToken replaceQuery(String newQuery);` replace the query part with a new query string

- `HistoryToken clearQuery();` remove all query parameters part

- `String query();` returns the query parameters string

- `String fragment();` returns the fragments part string

 - `HistoryToken removeFragment(String fragment);` remove a fragment from the fragments part

- `HistoryToken clear();` clear the the whole token and set it to root.

 - `String value();` return the string value representing the token.

all above methods will not directly change the browser history token, and will only make changes to the token instance, in order to apply the new token to the browser url you need to push a new state:

```
token = history().currrentToken();
//do some changes to the token
history().pushState(token.value());
```
also from the history you can move forward or back to simulate the browser forward and back buttons, by calling `history().forward()`/`history().back()`

 #### Listening to history changes

to listen to a history change you can add a listener to the history
`history().listen(state -> //do something here);`

the received state will contain a token instance.

or you can filter what token you want to listen to by passing a filter :

`history().listen(token -> //filter the token, state -> //do something when the filter match);`

there is a set of predefined token filters available for the use in the TokenFilter class

https://github.com/DominoKit/domino-mvp/blob/master/domino-api-shared/src/main/java/org/dominokit/domino/api/shared/history/TokenFilter.java

example

```
history()
   .listen(TokenFilter.startsWithPath("path1"), state -> //do something here)
   .onDirectUrl(state -> //do something if the filter match when user refresh or open a new window);
```

the onDirecturl is required if you need to execute something upon refresh or open a link in a new tap or window, since that will not trigger a popState even by the browser

**Comment by FrankHossfeld** [comment]
@vegegoku Thanks for charing you knowledge! Great point to start!

@slavap I will think about the request and see how I can get it into Nalu. Will take some time due holidays and so ...

**Comment by FrankHossfeld** [comment]
I am thinking about how the reload of a page will work.

In case we have a server running with http://lcoalhost:8080 and the host page added as welcome page, the host page will be loaded. Now, moving around, the url gets updated and might look like that: 
http://localhost:8080/applicationShell/person/detail/4
Now, reloading the host page with this url will cause a 404.
So, what am I doing wrong ...

**Comment by vegegoku** [comment]
maybe you need to have a default mapping to the index page and once the page is loaded then you can read the url using the history API.

in domino-mvp we do something like that. and it works

**Comment by FrankHossfeld** [comment]
Think, I have some problems with the default mapping. Server returns 404. Do you have an example web.xml?
The second part is already implemented.

**Comment by FrankHossfeld** [comment]
@slavap please, can you contact me at Gitter. Just finished the first implementation and would like to discuss it.

**Comment by FrankHossfeld** [comment]
Done.
