### ISSUE TITLE
Add methods for activation state to controller

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/nalu#30]
In some cases (caching controllers) there is a need to get control over activation state of contollers. For example if you route from one controller to another while caching is enabled. If the controller is already cached the method start would't be called. In this cases it would be useful to have methods `activate()` and `deactivate()` to do things when the component will be shown or hidden.

**Comment by TDesjardins** [comment]
@vegegoku Agree if they are called in these cases and could be overriden. Currently they are final and can't be overriden.

**Comment by FrankHossfeld** [comment]
Nalu uses these both methods, to tell the component, that it got attached or detached. So, they are more or less implement to trigger these method inside the component and part of the framework. 

In case the final key word gets removed, the developer, who override these method, has to make sure, that he calls super method. Otherwise, Nalu will not work correct. 

Thinking about it, I  would prefer adding the active and deactivate method  to the controller. They will be called nearly at the same time, but point to the controller. And it will reduce the risk, that a developer forget to call super.onAttach() and super.onDetach().

It is same with the widget class. There is a onAttach()-method and a onLoad() method.

**Comment by vegegoku** [comment]
I dont know why i would need those in the component ..since i am already in the view part where i can always add attach and detach handkers without needing those methods, my impression is that those method - how ever we name them - belongs to the controller where we have no access to the component implementation. And about the super call ot can ve avoided by hiding the base method and add new abstract or template method called by the super class methods.. what do you think?!

**Comment by FrankHossfeld** [comment]
I think, I added these methods because the Widget class has a onLoad and onUnload method. And, in case you are using native GWT or GXT widgets instead of Domino, Elemento or Elemental2 there might be such a method very helpful. And, regarding the possibility that Nalu is used outside the web, there might be the need for such methods. Of course you are right, you can do the same thing using the DetachHandler and AttachHandler. 

Regarding the controller, I like the idea having an activate and deactivate method, cause that fits well with the life cycle of start, mayStop and stop.   

MAy be, sometime we will change it again, but I think in the moment It's a good idea.
