### ISSUE TITLE
Feature Request: Allow Nalu app to be embedded into existing webpage.

### ISSUE THREAD

**Issue by schube** [NaluKit/nalu#34]
I am developing a little Nalu app. It will be an order form "living" in an existing webpage.
I think a div displayed as a popup or so.

This means I have no control over the URL which Nalu uses for routing. On the other side, I do not need to support deeplinking or "reload"ing the page and preserve states. 

According to Frank, "the current version does not support it. But it should be easy to do. "

So I am asking for this feature to be implemented!

Thank you,
Bernhard

**Comment by FrankHossfeld** [comment]
My current plan is to add two attributes to the `@Application`-annotation.

*  **hasHistory**: a boolean value that tells Nalu, wants to use history (a token inside the url) or not. The default value will be **true**. 
* **shellSelector**: a String value that tells Nalu which node to use, to append the shell. The default value is **root**, which tells Nalu to append the shell at the document root. Anything else will be interpreted as an ID and Nalu will search for that ID inside the DOM and append the shell as child of this node. In case the ID does not exist, Nalu will display an error message.

I will add a validation that checks, that in case a `shellSelector` is not equals 'root', the `hasHistory` value must be  **false**!

**Comment by FrankHossfeld** [comment]
Just implemented that Nalu works without using a history token. Will deploy a snapshot soon.

**Comment by vegegoku** [comment]
@schube @FrankHossfeld AFAIK nalu shell could use any widget, not necessary the domino-ui layout, now even though that the layout in domino-ui recently was wrapped inside a div by default, i wonder if the case here is use such layout, as for an embedded application i dont know if such layout is needed.

so i think this is a special case and we to know what kind of application we are going to embed and what layout it will use. i would like to know more about what kind of a shell needs to be embedded, because technically it works .. but what could be the best is what we need to figure out. and domino-ui has many options for such use case.

**Comment by FrankHossfeld** [comment]
@vegegoku You are right. It does not make really sense using a layout a footer, header and navigation embedded inside a web page. Sorry, my fault ... :-)

**Comment by FrankHossfeld** [comment]
implemented and ready to test!
